/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AlarmChart: typeof import('./src/components/alarmChart/index.vue')['default']
    AlarmMessage: typeof import('./src/components/alarmMessage/index.vue')['default']
    AlarmMessageItem: typeof import('./src/components/alarmMessageItem/index.vue')['default']
    BengChart: typeof import('./src/components/bengChart/index.vue')['default']
    BlackUser: typeof import('./src/components/blackUser/index.vue')['default']
    BoxTitle: typeof import('./src/components/boxTitle/index.vue')['default']
    CameraCoverage: typeof import('./src/components/cameraCoverage/index.vue')['default']
    CameraOverview: typeof import('./src/components/cameraOverview/index.vue')['default']
    DianyaChart: typeof import('./src/components/dianyaChart/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    NengxiaoChart: typeof import('./src/components/nengxiaoChart/index.vue')['default']
    ProprietorChart: typeof import('./src/components/proprietorChart/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RunningChart: typeof import('./src/components/runningChart/index.vue')['default']
    SafetyChart: typeof import('./src/components/safetyChart/index.vue')['default']
    SafetySituation: typeof import('./src/components/safetySituation/index.vue')['default']
    ShushiData: typeof import('./src/components/shushiData/index.vue')['default']
    VideoChart: typeof import('./src/components/videoChart/index.vue')['default']
    VideoChartt: typeof import('./src/components/videoChartt/index.vue')['default']
    VisitorChart: typeof import('./src/components/visitorChart/index.vue')['default']
  }
}
